### ISSUE TITLE
How do I select a subsription to which cloudshell will be attached?

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/vscode-azure-account#33]
Hello,

I have authenticated to azure and can see list of 10 subscriptions I have access to, when I launch cloudshell I'm not being asked which subscription I shall use and it picks one randomly looks like from the ones I have.
How do I indicate or switch to different subscription in cloud shell?

**Comment by chrmarti** [comment]
I think we should ask for which tenant to use. shell.azure.com does that too. With portal.azure.com there is also a tenant preselected.

**Comment by artisticcheese** [comment]
How is this supposed to work? My powershell terminal is just closing itself upon launch.

**Comment by chrmarti** [comment]
@artisticcheese Could you check if there is anything logged to the console (Help > Toggle Developer Tools)?

**Comment by artisticcheese** [comment]
![image](https://user-images.githubusercontent.com/13176884/37310225-3dde5324-2611-11e8-80a4-53adaba9d18f.png)

**Comment by chrmarti** [comment]
Does the terminal show anything before closing? When you are using an account with multiple tenants (directories), it should at some point show `Select directory...` and a picker should open after a short time at the top of the window.

**Comment by artisticcheese** [comment]
Terminal briefly flashes something and then closes without ability to see anything see below.
![2018-03-13_08-43-22](https://user-images.githubusercontent.com/13176884/37345385-d07a3bec-269a-11e8-91e6-25ef8a02eec6.gif)

**Comment by chrmarti** [comment]
@artisticcheese I have pushed a potential fix. Could you checkout this repository, launch it from VS Code and give it a try?

**Comment by artisticcheese** [comment]
How do I do that? (checkout repository and launch it from VS code)

**Comment by chrmarti** [comment]
You can:
- `git clone https://github.com/Microsoft/vscode-azure-account.git`
- Open the newly created `vscode-azure-account` folder in VS Code.
- Press F5, that will start a second window the Azure Account extension running from the checked out source.
- Open Powershell in Cloud Shell
- Check what is logged in the console (also when it worked).

**Comment by artisticcheese** [comment]
This logged into main window upon trying to launch cloud shell

```
C:\Program Files\Microsoft VS Code\Code.exe --debugBrkPluginHost=38733 --debugId=8a8a2f41-b5c6-49a8-b046-b7764bdd29e9 --extensionDevelopmentPath=D:\test\vscode-azure-account 
Activating extension 'ms-vscode.azure-account' failed: Cannot find module 'D:\test\vscode-azure-account\out\src\extension'.
extensionHostProcess.js:690
Activating extension `ms-vscode.azure-account` failed:  Cannot find module 'D:\test\vscode-azure-account\out\src\extension'
extensionHostProcess.js:453
Here is the error stack:  Error: Cannot find module 'D:\test\vscode-azure-account\out\src\extension'
extensionHostProcess.js:453
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.J.Y.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:671:784)
    at Module.require (module.js:498:17)
    at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
    at require (internal/module.js:20:19)
    at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:693:711
    at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:693:823)
    at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:692:740)
    at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:690:836)
    at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:920)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:539
    at Array.map (native)
    at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:452:514)
    at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:451:14)
    at t.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:691:203)
    at t.$activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:695:328)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:587:832)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:587:550)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:586:658)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:586:427)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:585:494
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:588:343
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:87:749
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:992)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:143:227)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)

```

**Comment by chrmarti** [comment]
Sorry, I forgot: After `git clone ...`, run `cd vscode-azure-account` and then `npm install`.

**Comment by artisticcheese** [comment]
`npm install` completed but error still the same 

```
PS D:\test> cd .\vscode-azure-account\
PS D:\test\vscode-azure-account> npm install

> azure-account@0.3.2 postinstall D:\test\vscode-azure-account
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.21.0
Found minimal version that qualifies engine range: 1.21.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/9a199d77c82fcb82f39c68bb33c614af01c111ba/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

added 354 packages in 29.033s
```

**Comment by artisticcheese** [comment]
Did not do much. here what is shown in second window

![image](https://user-images.githubusercontent.com/13176884/37371616-f8578ece-26dd-11e8-9230-b8126ee3cf92.png)

**Comment by chrmarti** [comment]
Sorry about that. I have published a new release with that change, could you update the installed extension and retry?

**Comment by artisticcheese** [comment]
This works but I still don't understand how do I switch subscriptions? I'm getting logged on into some random subscription from the list I have. Is it supposed to prompt me which one to use?

**Comment by chrmarti** [comment]
@artisticcheese It should ask you which tenant/directory (can be multiple subscriptions) to use. Does that work now? Even if it works: Could you check what is logged to the console and post it here?

**Comment by artisticcheese** [comment]
It was my fault, all is working.
