### ISSUE TITLE
VSCode failed to Azure sign in and cannot open Azure Bash after latest upgrade

### ISSUE THREAD

**Issue by mz1245** [microsoft/vscode-azure-account#801]
Does this occur consistently?  Yes
Repro steps:

1. Network offline and cannot login on
2. Cannot open Azure Bash shell

Action: azure-account.loginToCloud
Error type: AzureLoginError
Error Message: Offline

Version: 0.11.4
OS: win32
OS Release: 10.0.22000
Product: Visual Studio Code
Product Version: 1.78.0
Language: en

<details>
<summary>Call Stack</summary>

All works fine until last week VSCode upgrade automatically, (I just simple answered Yes ). I have uninstalled /re-install node.js, vscode et. al. But no luck!  Does anyone encounter the same problem last week after upgrade? 
```
extension.bundle.js:2:2468787extension.bundle.js:2:2468787
```

</details>

**Comment by mz1245** [comment]
![image](https://user-images.githubusercontent.com/77361671/236856588-f1b96952-d6fb-476f-950c-dced4dc0b4f3.png)
![image](https://user-images.githubusercontent.com/77361671/236857111-81dd5899-c78e-4fff-befe-29e0f805df22.png)

**Comment by JackH11** [comment]
My team and I are experiencing the same issue since about a week ago. We're working behind a company proxy and cannot connect to azure through the vscode extension. It seems it was cause by the latest update. I'm also getting this error: 
<img width="375" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/97849857/236931235-14fb3607-96a3-4774-9f39-4b350c868e52.png">

**Comment by varuns14** [comment]
I am also getting the same error after s/w upgrade. Would appreciate a fix on this.

**Comment by alexweininger** [comment]
I'm trying to find out if this was a result of the VS Code April 1.78 release or the recent 0.11.4 release of the Azure Account extension. Does downgrading the Azure Account extension to a previous version fix the issue? Does downgrading VS Code fix the issue?

@mz1245

**Comment by alexweininger** [comment]
> My team and I are experiencing the same issue since about a week ago. We're working behind a company proxy and cannot connect to azure through the vscode extension. It seems it was cause by the latest update. I'm also getting this error: <img alt="MicrosoftTeams-image (2)" width="375" src="https://user-images.githubusercontent.com/97849857/236931235-14fb3607-96a3-4774-9f39-4b350c868e52.png">

@JackH11 this looks like a different error than the original issue. Could you file a new issue and include specific details for your case? Thanks.

**Comment by mz1245** [comment]
> I'm trying to find out if this was a result of the VS Code April 1.78 release or the recent 0.11.4 release of the Azure Account extension. Does downgrading the Azure Account extension to a previous version fix the issue? Does downgrading VS Code fix the issue?
> 
> @mz1245

No, I just uninstalled and reinstalled latest version which is 1.78 /0.11.4 release (recommended).  It appears that the upgrade caused the problem as others reporting the same problem.

**Comment by mz1245** [comment]
Click wrong button (Issue not resolved).

**Comment by mz1245** [comment]
Just try downgrade to VSCodeUserSetup-x64-1.77.3 . First uninstalled the current one (1.78.1) and then installed, but right after installation complete, it appears that VSCode will automatically upgrade to the latest version (1.78.1). 

FYI. It is not me encountering this problem, but my teammates too with recent version upgrade.

**Comment by JackH11** [comment]
> 

It's the exact same issue coming after the new update. Running Azure Account v0.11.4. I start by getting the error "You appear to be offline". The issue certificate is an additional error I get after the appearing offline. Is there a way I can point the certificate to somewhere else?

**Comment by alexweininger** [comment]
A change released in the VS Code 1.78 April release breaks loading OS certificates on Windows. Meaning self-signed certificates and CA certificates picked up from a network proxy are currently broken. See https://github.com/microsoft/vscode/issues/181404 for more details.

It looks like VS Code is planning to include a fix in the [1.78.2 release (April recovery 2)](https://github.com/microsoft/vscode/issues/181866).

Until that is released, you can downgrade to VS Code 1.77. Also, [other users](https://github.com/microsoft/vscode-azure-account/issues/792#issuecomment-1540127373) have had success installing the [win-ca extension](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca), which makes Trusted Root Certificates on Windows available to VS Code extensions.

Another workaround if your CA certificate is provided by a network proxy is to configure the proxy related settings in VS Code.

**Comment by JackH11** [comment]
> A change released in the VS Code 1.78 April release breaks loading OS certificates on Windows. Meaning self-signed certificates and CA certificates picked up from a network proxy are currently broken. See [microsoft/vscode#181404](https://github.com/microsoft/vscode/issues/181404) for more details.
> 
> It looks like VS Code is planning to include a fix in the [1.78.2 release (April recovery 2)](https://github.com/microsoft/vscode/issues/181866).
> 
> Until that is released, you can downgrade to VS Code 1.77. Also, [other users](https://github.com/microsoft/vscode-azure-account/issues/792#issuecomment-1540127373) have had success installing the [win-ca extension](https://marketplace.visualstudio.com/items?itemName=ukoloff.win-ca), which makes Trusted Root Certificates on Windows available to VS Code extensions.
> 
> Another workaround if your CA certificate is provided by a network proxy is to configure the proxy related settings in VS Code.

Downgrading to VS Code 1.77 Fixed the issue for me

**Comment by alexweininger** [comment]
VS Code just released version 1.78.2 which should fix the certificates issue, could you please update VS Code and retry the operation?

**Comment by mz1245** [comment]
Tried on VS Code (Version 1.78.2) with Azure Account extension (v0.11.4), it still failed. However, when I downgraded Azure Account extension to previous version v0.11.3, the problem is fixed!  Thanks!

My solution is that VS Code version 1.78.2 plus Azure Account extension v0.11.3. 

Thanks!

![image](https://github.com/microsoft/vscode-azure-account/assets/77361671/ce567e4c-eebd-4d6b-a82f-380401dce39c)

**Comment by alexweininger** [comment]
@mz1245 weird, there should be no changes in v0.11.4 that impact cloud shell. Sorry to make you do this, but could you upgrade to v0.11.4 and try again? Thanks.

**Comment by mz1245** [comment]
It failed right after upgrade to v0.11.4

***@***.***

**Comment by alexweininger** [comment]
Could you share the logs when it fails? See the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.

**Comment by mz1245** [comment]
It appears that no problem to do sign in to Azure account, but it failed when open Azure Bash shell.  Here is the log for Window.

2023-05-11 19:05:55.351 [trace] KeybindingService#dispatch Enter [ No matching keybinding ]
2023-05-11 19:06:03.471 [trace] Stopped polling file:///c%3A/Users/mz1245/AppData/Roaming/Code/logs/20230511T182740/window1/renderer.log
2023-05-11 19:06:06.522 [trace] onWillActivateByEvent:  onTerminalProfile:azure-account.cloudShellBash
2023-05-11 19:06:06.524 [trace] CommandService#executeCommand _setContext
2023-05-11 19:06:06.633 [trace] terminalInstance#ctor (instanceId: 12) {"name":"Azure Cloud Shell (Bash)","executable":"node.exe","args":["-e","require('c:\\\\Users\\\\mz1245\\\\.vscode\\\\extensions\\\\ms-vscode.azure-account-0.11.4\\\\dist\\\\cloudConsoleLauncher').main()"],"icon":{"id":"azure"},"ignoreConfigurationCwd":true,"env":{"CLOUD_CONSOLE_IPC":"\\\\.\\pipe\\vscode-cloud-console-add2fe86edc023e890606e42075f14170031055c-sock"},"extHostTerminalId":"8b05b8b8-c744-4722-baf7-b23da546e8e4","isExtensionOwnedTerminal":true,"isTransient":true}
2023-05-11 19:06:06.676 [debug] Buffer content tracker: 0  lines cached
2023-05-11 19:06:06.677 [debug] Viewport content update complete,  0  lines in the viewport
2023-05-11 19:06:06.677 [debug] Buffer content tracker: set  0  lines
2023-05-11 19:06:06.709 [trace] Webgl was loaded
2023-05-11 19:06:06.758 [debug] Buffer content tracker: 0  lines cached
2023-05-11 19:06:06.758 [debug] Viewport content update complete,  7  lines in the viewport
2023-05-11 19:06:06.758 [debug] Buffer content tracker: set  7  lines
2023-05-11 19:06:06.765 [debug] Buffer content tracker: 0  lines cached
2023-05-11 19:06:06.765 [debug] Viewport content update complete,  0  lines in the viewport
2023-05-11 19:06:06.765 [debug] Buffer content tracker: set  0  lines
2023-05-11 19:06:06.779 [trace] [DEBOUNCE: Links] for vscode-terminal:/29a05e1056e2ad43353814aa14cbb116/12#accessible-buffer- is 1000ms
2023-05-11 19:06:06.851 [debug] Terminal process ready (shellProcessId: 2388)
2023-05-11 19:06:06.857 [debug] terminalInstance added capability 3
2023-05-11 19:06:08.621 [debug] Terminal process exit (instanceId: 12) with code undefined
2023-05-11 19:06:08.621 [debug] Terminal process exit (instanceId: 12) state 6
2023-05-11 19:06:08.621 [trace] terminalInstance#dispose (instanceId: 12)
2023-05-11 19:06:08.692 [debug] Buffer content tracker: 0  lines cached
2023-05-11 19:06:08.692 [debug] Viewport content update complete,  7  lines in the viewport
2023-05-11 19:06:08.692 [debug] Buffer content tracker: set  7  lines
2023-05-11 19:06:10.955 [trace] Started polling file:///c%3A/Users/mz1245/AppData/Roaming/Code/logs/20230511T182740/window1/renderer.log
2023-05-11 19:06:17.685 [trace] InteractiveSessionService#onWillSaveState: Persisting 0 sessions
2023-05-11 19:06:19.590 [trace] CommandService#executeCommand notification.clear
2023-05-11 19:06:20.669 [trace] CommandService#executeCommand notification.clear
2023-05-11 19:06:20.679 [trace] CommandService#executeCommand _setContext
2023-05-11 19:06:21.674 [error] Disconnecte

**Comment by mz1245** [comment]
AND also find this message in another log:

2023-05-11 19:07:13.048 [trace] Error while resolving configuration file 'vscode-userdata:/c%3A/Users/mz1245/AppData/Roaming/Code/User/tasks.json': Unable to read file 'vscode-userdata:/c:/Users/mz1245/AppData/Roaming/Code/User/tasks.json' (Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/mz1245/AppData/Roaming/Code/User/tasks.json')

There is no such tasks.json file in that directory, but instead, there is settings.json .

Hopefully this can help.

Sorry, I have to drop now.

Thanks,

Michael,


From: ZHANG, MICHAEL
Sent: Thursday, May 11, 2023 7:12 PM
To: microsoft/vscode-azure-account ***@***.***>
Subject: RE: [microsoft/vscode-azure-account] VSCode failed to Azure sign in and cannot open Azure Bash after latest upgrade (Issue #801)

It appears that no problem to do sign in to Azure account, but it failed when open Azure Bash shell.  Here is the log for Window.

2023-05-11 19:05:55.351 [trace] KeybindingService#dispatch Enter [ No matching keybinding ]
2023-05-11 19:06:03.471 [trace] Stopped polling file:///c%3A/Users/mz1245/AppData/Roaming/Code/logs/20230511T182740/window1/renderer.log
2023-05-11 19:06:06.522 [trace] onWillActivateByEvent:  onTerminalProfile:azure-account.cloudShellBash
2023-05-11 19:06:06.524 [trace] CommandService#executeCommand _setContext
2023-05-11 19:06:06.633 [trace] terminalInstance#ctor (instanceId: 12) {"name":"Azure Cloud Shell (Bash)","executable":"node.exe","args":["-e","require('c:\\\\Users\\\\mz1245\\\\.vscode\\\\extensions\\\\ms-vscode.azure-account-0.11.4\\\\dist\\\\cloudConsoleLauncher').main()"],"icon":{"id":"azure"},"ignoreConfigurationCwd":true,"env":{"CLOUD_CONSOLE_IPC":"\\\\.\\pipe\\vscode-cloud-console-add2fe86edc023e890606e42075f14170031055c-sock<file://.//pipe/vscode-cloud-console-add2fe86edc023e890606e42075f14170031055c-sock>"},"extHostTerminalId":"8b05b8b8-c744-4722-baf7-b23da546e8e4","isExtensionOwnedTerminal":true,"isTransient":true}
2023-05-11 19:06:06.676 [debug] Buffer content tracker: 0  lines cached
2023-05-11 19:06:06.677 [debug] Viewport content update complete,  0  lines in the viewport
2023-05-11 19:06:06.677 [debug] Buffer content tracker: set  0  lines
2023-05-11 19:06:06.709 [trace] Webgl was loaded
2023-05-11 19:06:06.758 [debug] Buffer content tracker: 0  lines cached
2023-05-11 19:06:06.758 [debug] Viewport content update complete,  7  lines in the viewport
2023-05-11 19:06:06.758 [debug] Buffer content tracker: set  7  lines
2023-05-11 19:06:06.765 [debug] Buffer content tracker: 0  lines cached
2023-05-11 19:06:06.765 [debug] Viewport content update complete,  0  lines in the viewport
2023-05-11 19:06:06.765 [debug] Buffer content tracker: set  0  lines
2023-05-11 19:06:06.779 [trace] [DEBOUNCE: Links] for vscode-terminal:/29a05e1056e2ad43353814aa14cbb116/12#accessible-buffer- is 1000ms
2023-05-11 19:06:06.851 [debug] Terminal process ready (shellProcessId: 2388)
2023-05-11 19:06:06.857 [debug] terminalInstance added capability 3
2023-05-11 19:06:08.621 [debug] Terminal process exit (instanceId: 12) with code undefined
2023-05-11 19:06:08.621 [debug] Terminal process exit (instanceId: 12) state 6
2023-05-11 19:06:08.621 [trace] terminalInstance#dispose (instanceId: 12)
2023-05-11 19:06:08.692 [debug] Buffer content tracker: 0  lines cached
2023-05-11 19:06:08.692 [debug] Viewport content update complete,  7  lines in the viewport
2023-05-11 19:06:08.692 [debug] Buffer content tracker: set  7  lines
2023-05-11 19:06:10.955 [trace] Started polling file:///c%3A/Users/mz1245/AppData/Roaming/Code/logs/20230511T182740/window1/renderer.log
2023-05-11 19:06:17.685 [trace] InteractiveSessionService#onWillSaveState: Persisting 0 sessions
2023-05-11 19:06:19.590 [trace] CommandService#executeCommand notification.clear
2023-05-11 19:06:20.669 [trace] CommandService#executeCommand notification.clear
2023-05-11 19:06:20.679 [trace] CommandService#executeCommand _setContext
2023-05-11 19:06:21.674 [error] Disconnecte

**Comment by hc-Jessie-Robbins** [comment]
I am also seeing similar issues with 1.78.2 and Azure Account v0.11.5 when trying to connect via the Azure Automation extension.  The logs I'm getting are:

2023-05-22 10:25:13.339 [info] MSAL: [Mon, 22 May 2023 15:25:13 GMT] : @azure/msal-node@1.14.6 : Info - getTokenCache called
2023-05-22 10:25:13.343 [info] Attempting to reach URL "https://login.microsoftonline.com/"...
2023-05-22 10:25:13.525 [error] self signed certificate in certificate chain
2023-05-22 10:25:13.527 [info] [Axios Request] POST https://login.microsoftonline.com/common/oauth2/devicecode?api-version=1.0
2023-05-22 10:25:13.753 [info] [Axios Response] 200 - POST https://login.microsoftonline.com/common/oauth2/devicecode?api-version=1.0
2023-05-22 10:25:13.762 [info] [Axios Request] POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-05-22 10:25:19.188 [info] [Axios Request] POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-05-22 10:25:24.517 [info] [Axios Request] POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-05-22 10:25:29.714 [info] [Axios Request] POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-05-22 10:25:30.162 [info] [Axios Response] 200 - POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-05-22 10:25:30.203 [info] [SubscriptionsClient Request] GET https://management.azure.com/tenants?api-version=2016-06-01
2023-05-22 10:25:30.268 [error] request to https://management.azure.com/tenants?api-version=2016-06-01 failed, reason: self signed certificate in certificate chain


I've also tried disabling everything but the Azure Account extension and it doesn't make a difference.  Downgrading to 0.11.3 as noted above also doesn't help.
