### ISSUE TITLE
Request to management.azure.com/subscriptions..... failed, reason: getaddrinfo ENOTFOUND management.azure.com

### ISSUE THREAD

**Issue by Tmpts21** [microsoft/vscode-azure-account#894]
Does this occur consistently?  Yes 
Repro steps:

1. Add Azure Tools Extension
2. Try to sign in to azure 
3. vscode redirectes me interactive sign in 
4. Successfully signed in
![image](https://github.com/microsoft/vscode-azure-account/assets/60459436/06177c9e-8b20-4d5a-8db8-0ec4e9ddd415)
5. Went back to vscode but i doesn't display any subscriptions.
5. Check Vscode console output  . It displays : ```request to https://management.azure.com/subscriptions?api-version=2016-06-01 failed, reason: getaddrinfo ENOTFOUND management.azure.com```

**BTW I am using my corporate laptop ( Is this some network issue  ? if so how can I resolve it ? )** 

Action: updateSubscriptionsAndTenants
Error type: REQUEST_SEND_ERROR
Error Message: request to redacted:url failed, reason: getaddrinfo ENOTFOUND redacted:url

Version: 0.11.6
OS: win32
OS Release: 10.0.22621
Product: Visual Studio Code
Product Version: 1.84.2
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:2:65384
NodeFetchHttpClient.<anonymous> extension.bundle.js:2:46552
step extension.bundle.js:2:2390802
Object.throw extension.bundle.js:2:2390907
rejected extension.bundle.js:2:2389632
```

</details>

**Comment by alexweininger** [comment]
Are you behind a proxy of any kind? Proxies often cause issues with sign-in. See the [Unable to Sign In While Using a Proxy section of our wiki](https://github.com/microsoft/vscode-azure-account/wiki/Troubleshooting#unable-to-sign-in-while-using-a-proxy) for possible fixes.

Also, see the [Enable and View Logs](https://github.com/microsoft/vscode-azure-account/wiki/Enable-and-view-logs) section of the wiki for how to capture and share Azure Account extension logs.

**Comment by Tmpts21** [comment]
I'm using my corporate laptop. So I think I am behind my corporate proxy

I tried running the command 

``` # Append to existing NO_PROXY environment variable
$Env:NO_PROXY += ',login.microsoftonline.com'

# Set the NO_PROXY environment variable for the first time
$Env:Foo = 'login.microsoftonline.com' ``` 

But still its not working.

**Comment by Tmpts21** [comment]
Full output log 

``` 2023-11-15 12:52:15.223 [info] [Axios Request] POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-11-15 12:52:15.748 [info] [Axios Response] 200 - POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-11-15 12:52:15.782 [info] [Axios Request] POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-11-15 12:52:16.319 [info] [Axios Response] 200 - POST https://login.microsoftonline.com/common/oauth2/token?api-version=1.0
2023-11-15 12:52:16.321 [info] [SubscriptionsClient Request] GET https://management.azure.com/tenants?api-version=2016-06-01
2023-11-15 12:52:16.357 [error] request to https://management.azure.com/tenants?api-version=2016-06-01 failed, reason: getaddrinfo ENOTFOUND management.azure.com
```

**Comment by alexweininger** [comment]
I see that the requests to `login.microsoftonline.com` are working, but the ones to `management.azure.com` are not. Can you try adding `management.azure.com` to the `NO_PROXY` environment variable too?

**Comment by Tmpts21** [comment]
Thanks for replying and helping me to resolve this issue. However I tried to add ``` NO_PROXY=management.azure.com ``` in environment variable but it still not working 

```
set NO_PROXY=management.azure.com
```

Then tried signing again its still produce same error.

Also here is my vscode proxy settings: 
![image](https://github.com/microsoft/vscode-azure-account/assets/60459436/8bd413b0-b62d-41b5-8eaf-8a08de86940d)

**Comment by alexweininger** [comment]
We just released v0.8.0 of the Azure Resources extension which fixes a lot of issues related to proxies and sign in. Update and try it again and see if that works. 

https://github.com/microsoft/vscode-azureresourcegroups/releases/tag/v0.8.0

**Comment by alexweininger** [comment]
You might want to reset your VS Code proxy settings back to the defaults.

**Comment by Tmpts21** [comment]
I updated the Azure resources to 0.8.0 and reset my proxy settings but still not working. It displays ``` Fetch Failed ```.  I look again at the azure account output it still says ``` request to https://management.azure.com/tenants?api-version=2016-06-01 failed, reason: getaddrinfo ENOTFOUND management.azure.com ```

**Comment by alexweininger** [comment]
Make sure you're using the command with the id `azureResourceGroups.logIn`, and not any others.
![image](https://github.com/microsoft/vscode-azure-account/assets/12476526/db50ffbf-c3d6-4702-9861-1b99071d3d57)
